### ISSUE TITLE
Fehler bei Checkip

### ISSUE THREAD

**Issue by lukiz-develop** [canoxnet/spdyn-updater#1]
Hey,

im Programmcode `spdynUpdater.c`  gibt es in der Zeile 68 einen Fehler bei der Domain von SPDYN.

Im Original steht:
`char * ipHost[NUMBER_IP_HOSTS] = { "checkip.spdy.de", "checkip.dyn.com", "checkip.dyn.org" }; // list of Hosts to check the IP`

Allerdings ist die Domain von SPDYN `checkip.spdyn.de`.

**Comment by canoxnet** [comment]
Danke für den Hinweis. Ist behoben
